#!/bin/sh
#
# search for all scripts and dotfiles, then open them with editor of choice
files=(~/.zshenv ~/.config/{bspwm,dunst,fontconfig,git,greenclip.cfg,gtk-3.0,htop,kitty,lazygit,lf,mimeapps.list,mozifire,mpd,mpv,ncmpcpp,neofetch,newsboat,npm,nvim,picom,polybar,rofi,sxhkd,user-dirs.dirs,X11,zsh}
    ~/bin/{scripts,cron,statusbar})
cfg() {
    find $files -type f |
        fzf --preview 'bat --color=always --line-range :50 {}' | xargs -r "$EDITOR"
}
