#!/bin/sh

# add color to commands
alias \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    dir='dir --color=auto' \
    vdir='vdir --color=auto' \
    grep='grep --color=auto' \
    fgrep='fgrep --color=auto' \
    egrep='egrep --color=auto'

type "exa" >>/dev/null &&
    alias \
        ls='exa --icons -F --color=always' \
        ll='exa --icons -Fl --color=always' \
        lla='exa --icons -Fla --color=always' ||
    alias \
        ls='ls -F --color=always' \
        ll='ls -Fl --color=always' \
        lla='ls -Fla --color=always'

#untar='tar -xvf' \
# shortcuts
alias \
    nuke='rm -rf' \
    sysinfo="inxi -Fxz" \
    icat='kitty +kitten icat' \
    vim='nvim' \
    v='nvim' \
    rm='rm -vI' \
    cp='cp -iv' \
    mv='mv -iv' \
    dot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' \
    weather='curl https://wttr.in/Buenos_Aires' \
    ..='cd ..' \
    ...='cd ../..' \
    ....='cd ../../..'

# search for all scripts and dotfiles, then open them with editor of choice
files=(~/.zshenv ~/.config/{bspwm,dunst,fontconfig,git,greenclip.cfg,gtk-3.0,htop,kitty,lazygit,lf,mimeapps.list,mozifire,mpd,mpv,ncmpcpp,neofetch,newsboat,npm,nvim,picom,polybar,rofi,sxhkd,user-dirs.dirs,X11,zsh}
    ~/bin/{scripts,cron,statusbar})
cfg() {
    find $files -type f |
        fzf --preview 'bat --color=always --line-range :50 {}' | xargs -r "$EDITOR"
}

# search for all notes and open selected one in editor
nt() {
    rg --files "$HOME"/notes |
        fzf --preview 'bat --color=always --line-range :50 {}' | xargs -r "$EDITOR"
}

# cd into note dir, live grep the contents of notes, then open in editor
live_search_notes() {
    cd "$HOME"/notes && interactove_fzf
}

# search for all git repos in folders I care, then cd into selected one.
all_git() {
    dir=$(find ~/{code,repos,notes} -type d -name .git | sed 's/\/.git//' |
        fzf --cycle --preview 'tree -C {} | head -50') && cd $dir && git status
}

# fd - cd into any hidden directory of the current folder
fcd() {
    dir=$(find "${1:-.}" -type d 2>/dev/null | fzf +m) && cd "$dir" || exit
}

# fkill - kill process
fkill() {
    pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')

    if [ "x$pid" != "x" ]; then
        echo "$pid" | xargs kill -"${1:-9}"
    fi
}

# cdf - cd into the directory of the selected file
cdf() {
    file=$(find "${1:-.}" -type f | fzf +m -q "$1") && dir=$(dirname "$file") && cd "$dir" || exit
}
