#! /bin/sh

# source pywal colors
. "${HOME}/.cache/wal/colors.sh"

sxhkd &

bspc monitor HDMI-0 -d I II III 
bspc monitor HDMI-1 -d IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

# Set border colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config active_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
