#! /bin/sh

# source pywal colors
# . "${HOME}/.cache/wal/colors.sh"

sxhkd &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           10

# Set border colors
bspc config normal_border_color "#c8ccd4"
bspc config focused_border_color "#61afef"
bspc config active_border_color "$color2"
bspc config active_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# --------------------------------------------
# ------------- Non-BSPWM related ------------
# --------------------------------------------
xrdb -load ~/.Xresources #reload Xresources
# launch polybar
# set wallpaper
xwallpaper --zoom ~/imgs/wallpapers/goku.png
# window compositor
picom -b -f &
xsetroot -cursor_name left_ptr &

# ------------- Autostart apps ---------------
# Polybar launch
$HOME/.config/polybar/launch.sh
# Flameshot screenshot utility
killall "flameshot"
flameshot &
# Dunst notification daemon
killall "dunst"
dunst &
